controller:
  kind: DaemonSet
  hostPort:
    enabled: true
  daemonset:
    useHostPort: true

  replicaCount: 1

  ## Solution provisoire pour le bug de l'Ingress NGINX 
  admissionWebhooks:
    failurePolicy: Ignore
    
  ingressClassResource:
    name: ingress-controller
    enabled: true
  ingressClass: ingress-controller

  # metrics:
  #   enabled: false
  #   serviceMonitor:
  #     enabled: false

  service:
    type: ClusterIP
