apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-writer
  namespace: nextcloud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud-writer-binding
  namespace: nextcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcloud-writer
subjects:
  - kind: ServiceAccount
    name: nextcloud-sa
    namespace: nextcloud
