apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake-store
spec:
  provider:
    fake:
      data:
        - key: "secret/nextcloud-credentials"
          value: |
            { "ADMIN_NAME": "admin",
              "ADMIN_PASSWORD": "admin" }
        - key: "secret/nextcloud-db"
          value: |
            { "username": "nextcloud",
              "password": "nextcloud",
              "uri": "postgres-db-cluster-rw.databases.svc.cluster.local:5432" }
        - key: "secret/db-nextcloud-user"
          value: |
            { "username": "nextcloud",
              "password": "nextcloud" }
        - key : "secret/openbao-init-vars"
          value: |
            { "ADMIN_PSW": "admin123",
              "ADMIN_NAME": "admin",
              "ADDRESS_OB": "http://openbao.openbao.svc.cluster.local:8200" }